In [1]:
# Dependencies
import requests
import json
import pandas as pd

In [9]:
AB = pd.read_csv('Resources/Chicago_listings.csv')
chicago_airbnb_df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2384,"Hyde Park - Walk to UChicago, 10 min to McCormick",2613,Rebecca,NaN,Hyde Park,41.78790,-87.58780,Private room,65,2,181,2020-10-29,2.43,1,355
1,4505,394 Great Reviews. 127 y/o House. 40 yds to tr...,5775,Craig & Kathleen,NaN,South Lawndale,41.85495,-87.69696,Entire home/apt,117,2,395,2020-07-14,2.71,1,184
2,7126,Tiny Studio Apartment 94 Walk Score,17928,Sarah,NaN,West Town,41.90289,-87.68182,Entire home/apt,70,2,389,2021-01-09,2.75,1,365
3,9811,Barbara's Hideaway - Old Town,33004,At Home Inn,NaN,Lincoln Park,41.91769,-87.63788,Entire home/apt,95,4,54,2021-01-15,0.65,11,282
4,10945,The Biddle House (#1),33004,At Home Inn,NaN,Lincoln Park,41.91183,-87.64000,Entire home/apt,125,4,21,2020-11-21,0.25,11,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6367,48199082,PVT ROOM|50% mthly OFF|15min walk to Kedzie BR...,211029191,Daniel,NaN,Irving Park,41.95488,-87.71000,Private room,41,4,0,NaN,NaN,5,180
6368,48199156,Stunning and spacious apt on Southport,378245394,Andrea,NaN,Lake View,41.95469,-87.66362,Entire home/apt,79,1,0,NaN,NaN,1,81
6369,48199227,BR with PRIVATE OFFICE in Old Irving Pk / Avon...,31378386,Proper Stays,NaN,Irving Park,41.94259,-87.72950,Private room,34,30,0,NaN,NaN,10,365
6370,48201067,Cosy loft,75724040,Aiste,NaN,Logan Square,41.92015,-87.71869,Entire home/apt,244,2,0,NaN,NaN,2,358
6371,48202487,Beautiful convertible in downtown Chicago,388904253,Arpita,NaN,Loop,41.88589,-87.61925,Entire home/apt,100,5,0,NaN,NaN,1,8